#!/usr/bin/env false
# CAO pipeline defaults — Stone et al. (2025) parameter values.
# DO NOT edit this file. Override values in namelist.sh instead.
# Format: KEY=VALUE  (no spaces around =, bash-sourceable)
# Lines beginning with # are ignored by both bash and the Python parser.

# ── Paths ──────────────────────────────────────────────────────────────────
# ERA5 hourly surface analysis archive root (RDA ds633.0)
ERA5_SFC=/glade/campaign/collections/rda/data/d633000/e5.oper.an.sfc
# Root directory for all pipeline output
SCRATCH_ROOT=/glade/derecho/scratch/zarzycki/CAO
# Directory containing this namelist and the pipeline scripts
SCRIPT_DIR=/glade/u/home/zarzycki/CAO
# TempestExtremes binary directory (used by steps 3 and 4)
TE_BIN_DIR=/glade/work/zarzycki/tempestextremes_casper/bin

# ── Year range ─────────────────────────────────────────────────────────────
# DEC_YEAR_START / DEC_YEAR_END: December-year of each DJF season, inclusive.
# e.g. DEC_YEAR_START=1979 → DJF 1979-80;  DEC_YEAR_END=2020 → DJF 2020-21
DEC_YEAR_START=1979
DEC_YEAR_END=2020

# ── Step 1 ─────────────────────────────────────────────────────────────────
# Number of parallel GNU-parallel workers for processing ERA5 months
NUMCORES=16

# ── Step 2 — detrend and standardize ──────────────────────────────────────
# Latitude bounds for the analysis domain (degrees N)
LAT_MIN=25.0
LAT_MAX=90.0
# Half-width (days) of the running-mean window applied to the climatology (21-day → 10)
HALF_WIN=10
# Detrending method: single_slope | per_doy
DETREND=single_slope
# Climatology reference period (Dec-years, inclusive); leave blank to use all years
REF_PERIOD_START=
REF_PERIOD_END=

# ── Step 3 — DetectBlobs ──────────────────────────────────────────────────
# Standardized-anomaly threshold for cold-air detection (negative = cold)
THRESHOLD=-2
# Radius of influence (degrees great-circle) applied after thresholding
RADIUS=1

# ── Step 4 — StitchBlobs ──────────────────────────────────────────────────
# Minimum blob size (grid cells per day) to retain a CAO
MIN_SIZE=1500
# Minimum duration (days) to retain a CAO
MIN_TIME=3
# Minimum overlap with the previous day's blob to continue a track (percent)
MIN_OVERLAP_PREV=50
